name: windows_management
description: Provides access to WinRT APIs from the Windows.Management
  namespace using FFI.
version: 0.0.1
homepage: https://win32.pub
repository: https://github.com/dart-windows/dartwinrt/tree/main/packages/windows_management
issue_tracker: https://github.com/dart-windows/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+windows_management%22
documentation: https://dartwinrt.dev
publish_to: none # TODO: Remove this

topics:
  - winrt
  - windows
  - ffi

environment:
  sdk: '^3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32: ^5.0.0
  windows_foundation:
    path: ../windows_foundation

dev_dependencies:
  test: ^1.24.1
